#!/usr/bin/env bash
#
# Flashback one-shot installer.
#
# Usage (cloud-init user-data on a fresh Ubuntu 22.04+ VPS):
#   curl -sSL https://raw.githubusercontent.com/Horizon-Digital-Engineering/flashback/main/deploy/install.sh | bash
#
# Or paste-and-run via SSH on a fresh box. Idempotent — re-running upgrades
# the stack in place without touching the Postgres password or token DB.
#
# What this script does:
#   1. Installs docker + the compose v2 plugin (no-op if already present)
#   2. Clones (or pulls) the repo into /opt/flashback
#   3. Generates a strong POSTGRES_PASSWORD on first run; reuses it after
#   4. Builds and starts the 4-service docker compose stack
#   5. Waits for /health on the server
#   6. Mints an initial admin token and writes it to /root/FLASHBACK_TOKEN.txt
#
# After completion: cat /root/FLASHBACK_TOKEN.txt for the bearer + endpoints.

set -euo pipefail

REPO_URL="${FLASHBACK_REPO_URL:-https://github.com/Horizon-Digital-Engineering/flashback.git}"
INSTALL_DIR="${FLASHBACK_INSTALL_DIR:-/opt/flashback}"
INITIAL_USER="${FLASHBACK_INITIAL_USER:-admin}"
TOKEN_FILE="${FLASHBACK_TOKEN_FILE:-/root/FLASHBACK_TOKEN.txt}"

log() { printf '\n[flashback-install] %s\n' "$*"; }

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "This installer must run as root (got uid $(id -u))." >&2
        exit 1
    fi
}

install_docker() {
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        log "docker + compose already installed — skipping"
        return
    fi
    log "Installing docker engine + compose plugin"
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ca-certificates curl gnupg lsb-release git openssl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        | tee /etc/apt/sources.list.d/docker.list >/dev/null
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
}

fetch_repo() {
    if [ -d "$INSTALL_DIR/.git" ]; then
        log "Updating $INSTALL_DIR"
        git -C "$INSTALL_DIR" fetch --depth 1 origin main
        git -C "$INSTALL_DIR" reset --hard origin/main
    else
        log "Cloning $REPO_URL → $INSTALL_DIR"
        mkdir -p "$(dirname "$INSTALL_DIR")"
        git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
    fi
}

ensure_env() {
    cd "$INSTALL_DIR"
    if [ ! -f .env ]; then
        local pg
        pg=$(openssl rand -hex 24)
        umask 077
        cat > .env <<EOF
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Treat as a secret. Do not commit. The Postgres data volume is tied to
# this password — rotating it requires also resetting the volume.
POSTGRES_PASSWORD=$pg
DATABASE_URL=postgres://flashback:$pg@db:5432/flashback
EOF
        chmod 600 .env
        log "Generated .env with strong POSTGRES_PASSWORD"
    else
        log ".env already exists — keeping existing POSTGRES_PASSWORD"
    fi
}

bring_up() {
    cd "$INSTALL_DIR"
    log "docker compose up -d --build (this can take a few minutes on first run)"
    docker compose up -d --build
}

wait_for_health() {
    log "Waiting for server /health ..."
    local i
    for i in $(seq 1 60); do
        if curl -sf http://localhost:8080/health >/dev/null 2>&1; then
            log "server is healthy after ${i}x 5s"
            return
        fi
        sleep 5
    done
    echo "[flashback-install] server did not become healthy in 5 minutes" >&2
    echo "    docker compose logs --tail 100 server" >&2
    exit 1
}

mint_initial_token() {
    cd "$INSTALL_DIR"
    if [ -f "$TOKEN_FILE" ]; then
        log "$TOKEN_FILE already exists — skipping initial mint"
        return
    fi
    log "Minting initial tokens for user=$INITIAL_USER"
    local public_ip token operator_token
    public_ip=$(curl -s --max-time 5 https://api.ipify.org || echo "<your-host>")
    # Two surfaces, two tokens: operator opens the admin UI, service is what
    # MCP/REST clients carry. Neither works on the other.
    token=$(docker compose exec -T server ./flashback token mint \
        --user="$INITIAL_USER" --name=initial-client \
        2>&1 | awk '/TOKEN:/ {print $2}')
    operator_token=$(docker compose exec -T server ./flashback token mint \
        --user="$INITIAL_USER" --name=admin-ui --role=operator \
        2>&1 | awk '/TOKEN:/ {print $2}')
    if [ -z "$token" ] || [ -z "$operator_token" ]; then
        echo "Failed to mint initial tokens. Check: docker compose logs server" >&2
        exit 1
    fi

    umask 077
    cat > "$TOKEN_FILE" <<EOF
Flashback is up.

  REST endpoint:  http://$public_ip:8080
  MCP endpoint:   http://$public_ip:8082/mcp
  Admin UI:       http://$public_ip:8080/admin

  SERVICE token  (MCP/REST clients):  $token
  OPERATOR token (admin UI sign-in):  $operator_token

How to use:
  - Add the MCP endpoint + the SERVICE token to your MCP client config
    (Claude Desktop / Cursor / Claude Code); the same token works for
    direct REST calls.
  - Sign in to the admin UI with the OPERATOR token. It sees every user's
    data and cannot call the API; the service token cannot open the UI.

Token plaintext is in this file only. Save it and delete this file when done:
  shred -u $TOKEN_FILE

Mint more tokens (one per client / user):
  cd $INSTALL_DIR && docker compose exec server ./flashback token mint --user=<u> --name=<label> [--role=operator]

List / revoke:
  docker compose exec server ./flashback token list
  docker compose exec server ./flashback token revoke <id>
EOF
    chmod 600 "$TOKEN_FILE"
    log "Wrote $TOKEN_FILE (mode 0600)"
}

main() {
    require_root
    install_docker
    fetch_repo
    ensure_env
    bring_up
    wait_for_health
    mint_initial_token
    log "Done. cat $TOKEN_FILE"
}

main "$@"
